name: Release to QA

on:
  workflow_dispatch:

jobs:
  tag-and-pr:
    runs-on: ubuntu-latest
    env: 
      working-directory: ./muddy-bar-2
    steps:
      - name: Repo Clone
        run: |
          git clone https://${{ secrets.GIT_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Checkout branch
        working-directory: ${{ env.working-directory }}
        run: |
            git checkout develop

      - name: Run Release to QA Workflow
        uses: crowdbotics/github-actions/release-to-qa@PLAT-13351
        with:
          working-directory: ${{ env.working-directory }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}