name: Release to QA

on:
  workflow_dispatch:

jobs:
  tag-and-pr:
    runs-on: ubuntu-latest
    env: 
      working-directory: ./muddy-bar-2
      base-branch: qa
      pr-branch: develop
      pr-label: automerge
    steps:
      - name: Repo Clone
        run: |
          git clone https://${{ secrets.GIT_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Checkout Reusable Actions Repository
        uses: actions/checkout@v2
        with:
          repository: 'sgmagar/github-actions'
          path: 'github-actions'

      - name: Checkout branch
        working-directory: ${{ env.working-directory }}
        run: |
            git checkout ${{ env.pr-branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

      - name: Run Release to QA Workflow
        uses: ./github-actions/release-to-qa
        with:
          working-directory: ${{ env.working-directory }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          base-branch: ${{ env.base-branch }}
          pr-branch: ${{ env.pr-branch }}
          pr-label: ${{ env.pr-label }}
